### ISSUE TITLE
Rather than REST... how about a "state" based web socket service?

### ISSUE THREAD

**Issue by howardroark** [GeppettoJS/todomvc.geppetto#1]
**Get ready to be open-minded :)**

I want to propose a pattern here that does not really exist out in the wild, but really should.  I have experimented with the idea in the past and had success (I'm a hacky coder though).  The idea is essentially that your app is reflected in the "state" of your collections and models.  This is likely already true in the example because of the need to keep the "state" in local storage.  The trick is to focus on it as being your "DOM".

The idea is to go one step further and mirror the state in a Mongo cluster via web-sockets.  Your end objective is to enable many devices to mirror the same "state" through the cluster (as a sort of portal).  For example you may have your TODO list open on your phone and desktop.  Each time you adjust the "state" you would want it to be mirrored on each device, and instantly.

Having the cluster in place also offers a unique opportunity to have peripheral services running that could interject upon an individual "state".  For example the central service may offer an extended UI that allows someone you trust to drop new "items" into your "state".   Or maybe it watches your "state" and notifies via email when some "items" grow stale.

There are a number of questions yet to be answered, I do get that. Does the service simply pass the device a snapshot of the "state" which the device then has to preform a diff on?  Or does the service itself do the hard work?

---

We are building a time tracking tool (open-source) that aims to run based on this exact philosophy.  The down the road goal is to have a public central service and a privately deployable version. I work in an industry where tracking your time for each job is essential. There is just nothing out there that works the way people think, and nothing that can easily pair with other services.  It is slow moving though because I am teaching someone how to code as they build it.  I personally don't really like programming, I just like thinking about how something should be designed :P

It's just a thought, but I think distilling a pattern like this could have huge wins for the greater community.  At the very least it would be cool to have your thoughts on the matter.  I have been following this project because I really feel that the **triumvirate** would be key to getting it right.  I also love that you just taught me that word!!!

There is a project out in the wild that could be something to build upon for the service... https://github.com/scttnlsn/backbone.io

This is our project (it's a bit of a playground right now)...
https://github.com/openops/mom

**Comment by creynders** [comment]
I'd definitely use Meteor to go down that road, which takes care of most of the real-time syncing for you. For an example application like TodoMVC the whole's a bit too elaborate IMO. I want to keep the backend very, very simple: just a simple restify app that exposes the todos.

Thanks for the link to Backbone.io, didn't know it yet! Will definitely come in handy one time or another.

**Comment by howardroark** [comment]
Fair enough!  (I was mainly fishing for the use of your brain, which I enjoy)

Meteor is totally my inspiration! The "mini-mongo" implementation is so cool. Though in my view Meteor is more of a "Rails" killer, and is designed for pumping out "start up" apps. It sort of distills what it is that everyone is already trying to do but don't quite realize it yet. The core ideas are wonderful, but it goes really far down the road of making things magic.  I like to avoid magic things because at a certain point you can't evolve them any more.  I also have an issue with most start-up apps in that they try to revolutionize the way people do things.  They all tend to offer a "new approach" to life.  I feel only people with the mind set of a developer/product designer can really make solid use of these types of ideas.  I have witnessed first hand how ideas like Basecamp continuously fail when introduced to any organization with a wide range of mentalities.

I totally get your instinct to say that this is too elaborate for a TODO app.  Though, I feel the opposite way.  In my view the tools which have the most success are the ones that can be "grokked" by the largest audience.  It's sort of like following the UNIX philosophy for tools.  Why not target these ideas and extend their usefulness. 

To me a TODO app is essentially an interface to manipulate a schema. Everyone understands the nature of the TODO app and it could easily be distilled to a JSON format.  Once you have the core schema down pat you can build up the pattern of mirroring the "state" across devices and systems.  This allows you to manipulate the schema in different contexts and enables for a variety of representations in real time.  For example you may manipulate the TODO schema on your smart phone while the same schema is represented in a digital picture frame above where you hang your keys.  To me the beauty of this idea is that I can explain the nature of the process in it's entirety to a baby-boomer.  The trick is to convince a developer to give a shit, haha.

Hence, my trolling.... You are always a good sport though!
